## Xarray
`zarray`: 
- python package 
- augments Numpy array by adding labeled dimensions, coordinates, and attributes 
- based on NetCDF data model 

Today: learn `xarray.DataArray` and `xarray.Dataset`

## `xarrat.DataArray`
-priamry object of `xarray`
- it is an n=dimensional array with **labeled dimensions*
- represents a single varibale in the netCDF data format: holds the variables values, dimensions, and attributes 

In `xarray` each dimension has a set of **coordiantes**
A dimensions coordinates indicate the dimensions values (tick labels along the dimension)

# Create an `xarray.DataArray`

We will use the info in our example. 

### Libraries

In [1]:
import os 
import pandas as pd 
import numpy as np 

import xarray as xr #new package alert!!!

** Variable values**

Underlying data in an `xr.DataArray` is a `numpy.array` that holds the variabel vaclues 

We start by making a `np.array` of our mock temperature data 



In [2]:
# values of a single variabel (temp) at each poitn fo the coords 

temp_data = np.array([np.zeros((5,5)), #3 numpy arrays which represenets 1 day of data, #give sus an array of whatever dimensison we give it of zeros 
                      np.ones((5,5)), 
                      np.ones((5,5))*2]).astype(int)
temp_data

#temp is in celsius, 1 dimension is time, lat and long and also first day is september 1st, second is 2nd
#xarray allows you to add this 

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]])

**Dimensions and Coordinates**

To specify the dimensiosn of our `xr.DataArray`, lets think about how we construct the `np.array` which holds the data. 
- first dimension: time
- 2D numpy array: indexing starts in top left corner (indeixng is same as matrices)(row, column)(2nd index is latitude)
- longitude: 3rd dimension  

coordinates(Values of each dimension) 
- time coord is 3 days
- latitude (noteice decreasing order)( want visual rows to align with coordinates)
- numpy indexing top left corner: 
- if passes 0 lat it would be -10, -20 continued 

value in cell

We have: 
- 1st dimension: time, coords: 2022-09,01,2022-09,02, 2022-09,03
- 2nd dimension: latitude, coords: from 70 to 30, decreasing by 10 
- 3rd dimension: longitude, coords: from 60 to 100, icnreaisn gby 100

Add dims and coordS: 



In [3]:
#names of dinensions in requried order

# names of the dimensions in the required order
dims = ('time', 'lat', 'lon')

# create coordinates to use for indexing along each dimension 
coords = {'time' : pd.date_range("2022-09-01", "2022-09-03"),
          'lat' : np.arange(70, 20, -10),
          'lon' : np.arange(60, 110, 10)}  


In [4]:
np.arange(60,110,10) #starts at 60 goes to 110 and increases by 10



array([ 60,  70,  80,  90, 100])

In [5]:
#standard dictionary 
attrs = { 'title' : 'temperature across weather stations',
          'standard_name' : 'air_temperature',
          'units' : 'degree_c'}

In [6]:
attrs

{'title': 'temperature across weather stations',
 'standard_name': 'air_temperature',
 'units': 'degree_c'}

## Subsetting 

- To subset data from xarray data.array need to specify subsets we want along each dimension 
- can do this in two ways 
- relyign ond imensions positions (**dimension looup by position**)
- by callign each dimension by its name (**ddimensions lookup by name**)

**Examples**

We want the temperature recorded by the weater station located at 40N 80E on September 1st, 2022


In [7]:
temp = xr.DataArray(data = temp_data, 
                    dims = dims,
                    coords = coords,
                    attrs = attrs)
temp

#have an array udnerlying data numerical values, dimensiosn in specific order time lat long,
#how many values on that dimension

#number of coordinates along dimension, time:3, lat:5, long:5

<xarray.DataArray (time: 3, lat: 5, lon: 5)>
array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]])
Coordinates:
  * time     (time) datetime64[ns] 2022-09-01 2022-09-02 2022-09-03
  * lat      (lat) int64 70 60 50 40 30
  * lon      (lon) int64 60 70 80 90 100
Attributes:
    title:          temperature across weather stations
    standard_name:  air_temperature
    units:          degree_c

In [8]:
#temp[0,3,2] 0 index says going into 2 x 2 array, going 3rd position (40) and 2 means index 2 (80), if for 2nd day the 0 would be 1 
# acess diennsions by position then use labels for indexing 
#temp.loc['2022-09-01', 40, 80] #pandas df has 2 axis then lco to access thigns along loc by values of axis
#xarray
#by label: 

## Reduction 

`xarray` has several methods to reduce an `xarray.DataArray` along any number of dimensions 

**Example**

calcualte average temperature at each station over time: 


In [9]:
avg_temp = temp.mean(dim = 'time')
avg_temp

<xarray.DataArray (lat: 5, lon: 5)>
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])
Coordinates:
  * lat      (lat) int64 70 60 50 40 30
  * lon      (lon) int64 60 70 80 90 100

In [10]:
avg_temp.attrs = {'title': 'average temperature over 3 days'}
avg_temp

<xarray.DataArray (lat: 5, lon: 5)>
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])
Coordinates:
  * lat      (lat) int64 70 60 50 40 30
  * lon      (lon) int64 60 70 80 90 100
Attributes:
    title:    average temperature over 3 days

## `xarray` 

`xarray.DataSet` :
- resembles an in-memory representation of a NetCDF file 
- consists of multiple variables (each variable is an `xarray.DataArray`)
- self describing
- attibutes can belong to a variable, or dimension, or describe the whole dataset 
- variable sin an `xarray.DataSet` can have the same dimensions, share some dimensions, or have no dimensions in commonn 

**Example**

Combine temperature avg temperature data into a single object:

In [11]:
#make dictionarues with variables and attributes
data_vars = {'avg_temp': avg_temp,
            'temp' : temp}

attrs = {'title': 'temperature data at weather stations: daily and average',
         'description': 'simple example of xarray.DataSet'}
         
#create xarray.DataSet
temp_dataset = xr.Dataset ( data_vars = data_vars,
                          attrs = attrs)

temp_dataset

#whole dataset has 3 dimensions lat long and time

<xarray.Dataset>
Dimensions:   (lat: 5, lon: 5, time: 3)
Coordinates:
  * lat       (lat) int64 70 60 50 40 30
  * lon       (lon) int64 60 70 80 90 100
  * time      (time) datetime64[ns] 2022-09-01 2022-09-02 2022-09-03
Data variables:
    avg_temp  (lat, lon) float64 1.0 1.0 1.0 1.0 1.0 1.0 ... 1.0 1.0 1.0 1.0 1.0
    temp      (time, lat, lon) int64 0 0 0 0 0 0 0 0 0 0 ... 2 2 2 2 2 2 2 2 2 2
Attributes:
    title:        temperature data at weather stations: daily and average
    description:  simple example of xarray.DataSet

palmer penguins doesnt have dimensions to it ijsut tabular data this is good for multi dimensional data 